; cmsGO!
;
; @author Pixels & Points GmbH <info@pixels-points.ch>
; @copyright Copyright (c) 2002-2023, Pixels & Points GmbH
; @license https://www.pixels-points.ch/cmsgo-license.html Pixels & Points cmsGO! license

; Use this INI file to add custom URL to the Google Sitemap
; ---------------------------------------------------------
; we just use the simplest sitemap format here
; should be enough, visit http://www.google.com/webmasters/sitemaps/
; to learn more about Google sitemaps

;[1]
;url  = "https://www.pixels-points.ch/"
;date = "2006-07-26"

;[2]
;url  = ""
;date = ""

; ...and so on
