	<?php
/*********************************************************************************************
 V1.1  31.12.09 K.Heermann (flip-flop)
 "LightBox Prev/Next all": All LightBox images bind up
 New rel for all LB pictures is called: rel="lightbox[catid-XX]"
 Where XX is the current category ID.
 Update 05.08.2011 KH: If no category is specified in the array
 Update 19.01.2012 KH: Bug correction at "all image CPs and no gallery images:"
                       RegEx [^gallery] changed to (?!gallery)
 
 Filename: rt_lighbox_prev_next_all01.php
 Folder:   /template/inc_script/frontend_render/
 Switch:   $phpwcms['allow_ext_render'] = 1; (/config/phpwcms/conf.inc.php)
 
**********************************************************************************************/
 
// -------------------------------------------------------------------------------------------
// obligate check for phpwcms constants
  if (!defined('PHPWCMS_ROOT')) {
    die("You Cannot Access This Script Directly, Have a Nice Day."); }
// -------------------------------------------------------------------------------------------
 
// ===== CUSTOM INPUT ========================================================================
 
// ------ Some parameters if LightBox for images is set
$inc_categories    = true;    // true = include active,   false = exclude active

// ------ Fill in your inc/excluded categories e.g. array(7,23,16,25,33)
$_categories       = array( );

// ------ Template range
// begin - end of triggered content marked in template with <!-- bbbbbbbb //-->{CONTENT}<!-- eeeeeee //-->
$tag_before        = 'Layout Moderna Subseiten Start';  // Marking text for the beginning of the content to be scanned e.g. <!-- content-begin //-->
$tag_after         = 'Layout Moderna Ende';    // Marking text for the end of the content to be scanned e.g. <!-- content-end //-->

// ------ Some specific parameters
$one_image_on      = true;    // true = include images without prev/next (one image),   false = exclude ...
$article_list_on   = false;   // true = include article images in article list mode,   false = exclude ...
$gallery_on        = false;   // true = include images generated by gallery script,   false = exclude ...


 
// ===========================================================================================
 
 
$text = '';
 
$cat_id     = $content['cat_id'];    // current category ID
 
if (count($_categories) == 0 ) $_categories[0] = $cat_id;  // Update 05.08.2011 KH: If no category is specified in the array
 
if ($inc_categories ) {  // include active?
 
    if ( in_array($cat_id, $_categories) ) {
        $text = preg_match("/\<!-- content-begin \/\/--\>(.*?)\<!-- content-end \/\/--\>/ism", $content['all'], $g) ? $g[1] : '';
        $text = preg_match("/\<!-- $tag_before \/\/--\>(.*?)\<!-- $tag_after \/\/--\>/ism", $content['all'], $g) ? $g[1] : '';
   }
}
 
else { // exclude active!
 
    if ( !in_array($cat_id, $_categories) ) {
 
        $text = preg_match("/\<!-- $tag_before \/\/--\>(.*?)\<!-- $tag_after \/\/--\>/ism", $content['all'], $g) ? $g[1] : '';
    }
 
}
 
    if ( !$article_list_on AND ($content['list_mode'] == true) ) $text = '';  // in article list mode and include article images?
 
 
    // ------- lets go and pic up the images
    if (!empty ($text)) {
 
 
       if ($gallery_on) // all image CPs and the images from gallery too
 
          $text = preg_replace('/rel="lightbox\[(.*?)\]"/','rel="lightbox[catid-'.$cat_id.']"', $text);  // fill content
 
       else // all image CPs and no gallery images
 
          $text = preg_replace('/rel="lightbox\[(?!gallery).*?\]"/i',
           'rel="lightbox[catid-'.$cat_id.']"', $text);  // fill content
 
 
       if ($one_image_on)  // images without prev/next (one image) like CP text w/image
 
       $text = str_replace('rel="lightbox"','rel="lightbox[catid-'.$cat_id.']"', $text);
 
 
       // And write it back
       $content['all'] = preg_replace("/\<!-- $tag_before \/\/--\>(.*?)\<!-- $tag_after \/\/--\>/ism",
               $text, $content['all']);  // fill content
    }
 
 
// -----------[ CLOSE ]----------------
?>